### ISSUE TITLE
cray-libsci versions through CPE 22.11 don't work with OneAPI >= 2022.2

### ISSUE THREAD

**Issue by vanderwb** [NCAR/spack-gust#42]
The problem occurs if using OpenMP-enabled libraries:

```
[10:52] hello_world$ cc -o test openmp.c -qopenmp
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is
 the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
openmp.c(29): warning #266: function "sched_getcpu" declared implicitly
                core        = sched_getcpu() % TASKS_PER_NODE;
                              ^

/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /opt/cray/pe/libsci/22.11.1.2/INTEL/19.0/x86_64/lib/libsci_intel_mp.so: undefined reference to `__svml_idiv16_b3'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /opt/cray/pe/libsci/22.11.1.2/INTEL/19.0/x86_64/lib/libsci_intel_mp.so: undefined reference to `__svml_idiv16_mask_b3
'
```

**Comment by vanderwb** [comment]
Removed from the module stack.
